# ch05 quiz1

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

## 불리언 통계량

1.영화 데이터셋을 로드하여 상영 시간(duration)이 2시간이 넘는 영화의 개수를 확인하세요.

In [2]:
movie = pd.read_csv('../data/movie.csv')

In [3]:
(movie['duration'] > 120).sum()

1039

In [4]:
movie['duration'].gt(120).sum()

1039

2.전체 영화 중 상영 시간이 2시간이 넘는 영화의 비율을 확인하세요.

In [5]:
movie['duration'].dropna().gt(120).mean()

0.21199755152009794

- 누락값이 있으면 평균에 오차가 발생하므로 누락값을 먼저 처리

- value_counts(normalize=True)로 검증할 수 있다.

In [6]:
movie['duration'].dropna().gt(120).value_counts(normalize=True)

False    0.788002
True     0.211998
Name: duration, dtype: float64

## 다중 불리언 조건

2.영화 데이터셋을 로드하여 평점(imdb_score)이 8점 이상, 등급(content_rating)이 PG-13, 2000년~2009년 사이에 출시(titie_year)된 영화를 찾으세요.

In [7]:
movie = pd.read_csv('../data/movie.csv', index_col='movie_title')

In [8]:
crit1 = movie['imdb_score'] >= 8

In [9]:
crit2 = movie['content_rating'] == 'PG-13'

In [10]:
crit3 = (movie['title_year'] >= 2000) & (movie['title_year'] <= 2009)

In [11]:
crit_all = crit1 & crit2 & crit3

In [12]:
movie[crit_all].head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
The Dark Knight,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,4667.0,English,USA,PG-13,185000000.0,2008.0,13000.0,9.0,2.35,37000
Batman Begins,Color,Christopher Nolan,478.0,128.0,22000.0,11000.0,Liam Neeson,23000.0,205343774.0,Action|Adventure,...,2685.0,English,USA,PG-13,150000000.0,2005.0,14000.0,8.3,2.35,15000
Star Trek,Color,J.J. Abrams,518.0,127.0,14000.0,981.0,Leonard Nimoy,26000.0,257704099.0,Action|Adventure|Sci-Fi,...,1559.0,English,USA,PG-13,150000000.0,2009.0,12000.0,8.0,2.35,19000
The Bourne Ultimatum,Color,Paul Greengrass,329.0,115.0,521.0,883.0,Edgar Ramírez,13000.0,227137090.0,Action|Mystery|Thriller,...,820.0,English,USA,PG-13,110000000.0,2007.0,897.0,8.1,2.35,0
Pirates of the Caribbean: The Curse of the Black Pearl,Color,Gore Verbinski,271.0,143.0,563.0,1000.0,Orlando Bloom,40000.0,305388685.0,Action|Adventure|Fantasy,...,2113.0,English,USA,PG-13,140000000.0,2003.0,5000.0,8.1,2.35,10000

In [13]:
movie[crit_all].shape

(23, 27)

## 불리언 인덱싱

2-1. 모든 조건에 부합되는 영화의 평점, 등급, 출시년도를 모아 별도의 DataFrame을 생성하세요.

In [14]:
movie2 = movie[crit_all]

In [15]:
movie3 = movie2[['imdb_score', 'content_rating', 'title_year']]

In [16]:
movie3

,imdb_score,content_rating,title_year
movie_title,,,
The Dark Knight,9.0,PG-13,2008.0
Batman Begins,8.3,PG-13,2005.0
Star Trek,8.0,PG-13,2009.0
The Bourne Ultimatum,8.1,PG-13,2007.0
Pirates of the Caribbean: The Curse of the Black Pearl,8.1,PG-13,2003.0
The Lord of the Rings: The Fellowship of the Ring,8.8,PG-13,2001.0
Casino Royale,8.0,PG-13,2006.0
The Lord of the Rings: The Return of the King,8.9,PG-13,2003.0
The Lord of the Rings: The Two Towers,8.7,PG-13,2002.0
Cinderella Man,8.0,PG-13,2005.0
A Beautiful Mind,8.2,PG-13,2001.0
Big Fish,8.0,PG-13,2003.0
The Pursuit of Happyness,8.0,PG-13,2006.0
Catch Me If You Can,8.0,PG-13,2002.0
The Prestige,8.5,PG-13,2006.0
Serenity,8.0,PG-13,2005.0
Million Dollar Baby,8.1,PG-13,2004.0
Hotel Rwanda,8.1,PG-13,2004.0
The Diving Bell and the Butterfly,8.0,PG-13,2007.0
The Sea Inside,8.1,PG-13,2004.0
Sicko,8.0,PG-13,2007.0
Persepolis,8.0,PG-13,2007.0
Lage Raho Munna Bhai,8.2,PG-13,2006.0

In [17]:
movie4 = movie[crit_all][['imdb_score', 'content_rating', 'title_year']]

In [18]:
movie4

,imdb_score,content_rating,title_year
movie_title,,,
The Dark Knight,9.0,PG-13,2008.0
Batman Begins,8.3,PG-13,2005.0
Star Trek,8.0,PG-13,2009.0
The Bourne Ultimatum,8.1,PG-13,2007.0
Pirates of the Caribbean: The Curse of the Black Pearl,8.1,PG-13,2003.0
The Lord of the Rings: The Fellowship of the Ring,8.8,PG-13,2001.0
Casino Royale,8.0,PG-13,2006.0
The Lord of the Rings: The Return of the King,8.9,PG-13,2003.0
The Lord of the Rings: The Two Towers,8.7,PG-13,2002.0
Cinderella Man,8.0,PG-13,2005.0
A Beautiful Mind,8.2,PG-13,2001.0
Big Fish,8.0,PG-13,2003.0
The Pursuit of Happyness,8.0,PG-13,2006.0
Catch Me If You Can,8.0,PG-13,2002.0
The Prestige,8.5,PG-13,2006.0
Serenity,8.0,PG-13,2005.0
Million Dollar Baby,8.1,PG-13,2004.0
Hotel Rwanda,8.1,PG-13,2004.0
The Diving Bell and the Butterfly,8.0,PG-13,2007.0
The Sea Inside,8.1,PG-13,2004.0
Sicko,8.0,PG-13,2007.0
Persepolis,8.0,PG-13,2007.0
Lage Raho Munna Bhai,8.2,PG-13,2006.0

In [19]:
movie5 = movie.loc[crit_all, ['imdb_score', 'content_rating', 'title_year']]

In [20]:
movie5

,imdb_score,content_rating,title_year
movie_title,,,
The Dark Knight,9.0,PG-13,2008.0
Batman Begins,8.3,PG-13,2005.0
Star Trek,8.0,PG-13,2009.0
The Bourne Ultimatum,8.1,PG-13,2007.0
Pirates of the Caribbean: The Curse of the Black Pearl,8.1,PG-13,2003.0
The Lord of the Rings: The Fellowship of the Ring,8.8,PG-13,2001.0
Casino Royale,8.0,PG-13,2006.0
The Lord of the Rings: The Return of the King,8.9,PG-13,2003.0
The Lord of the Rings: The Two Towers,8.7,PG-13,2002.0
Cinderella Man,8.0,PG-13,2005.0
A Beautiful Mind,8.2,PG-13,2001.0
Big Fish,8.0,PG-13,2003.0
The Pursuit of Happyness,8.0,PG-13,2006.0
Catch Me If You Can,8.0,PG-13,2002.0
The Prestige,8.5,PG-13,2006.0
Serenity,8.0,PG-13,2005.0
Million Dollar Baby,8.1,PG-13,2004.0
Hotel Rwanda,8.1,PG-13,2004.0
The Diving Bell and the Butterfly,8.0,PG-13,2007.0
The Sea Inside,8.1,PG-13,2004.0
Sicko,8.0,PG-13,2007.0
Persepolis,8.0,PG-13,2007.0
Lage Raho Munna Bhai,8.2,PG-13,2006.0

3.대학 데이터셋을 읽어 텍사스 주에 있는 모두 대학을 선택하세요.

In [21]:
college = pd.read_csv('../data/college.csv')

In [22]:
college[college['STABBR'] == 'TX'].head()

,INSTNM,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
3610,Abilene Christian University,Abilene,TX,0.0,0.0,0.0,1,530.0,545.0,0.0,...,0.0454,0.0423,0.0045,0.0468,1,0.2595,0.5527,0.0381,40200,25985
3611,Alvin Community College,Alvin,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0002,0.0000,0.0143,0.7123,1,0.1549,0.0625,0.2841,34500,6750
3612,Amarillo College,Amarillo,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0000,0.0001,0.0085,0.6922,1,0.3786,0.1573,0.3431,31700,10950
3613,Angelina College,Lufkin,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0264,0.0005,0.0000,0.5600,1,0.5308,0.0000,0.2603,26900,PrivacySuppressed
3614,Angelo State University,San Angelo,TX,0.0,0.0,0.0,0,475.0,490.0,0.0,...,0.0285,0.0331,0.0011,0.1289,1,0.4068,0.5279,0.1407,37700,21319.5

In [23]:
college[college['STABBR'] == 'TX'].shape

(472, 27)

In [24]:
college2 = college.set_index('STABBR')

In [25]:
college2.loc['TX'].head()

,INSTNM,CITY,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
STABBR,,,,,,,,,,,,,,,,,,,,,
TX,Abilene Christian University,Abilene,0.0,0.0,0.0,1,530.0,545.0,0.0,3572.0,...,0.0454,0.0423,0.0045,0.0468,1,0.2595,0.5527,0.0381,40200,25985
TX,Alvin Community College,Alvin,0.0,0.0,0.0,0,NaN,NaN,0.0,4682.0,...,0.0002,0.0000,0.0143,0.7123,1,0.1549,0.0625,0.2841,34500,6750
TX,Amarillo College,Amarillo,0.0,0.0,0.0,0,NaN,NaN,0.0,9346.0,...,0.0000,0.0001,0.0085,0.6922,1,0.3786,0.1573,0.3431,31700,10950
TX,Angelina College,Lufkin,0.0,0.0,0.0,0,NaN,NaN,0.0,3825.0,...,0.0264,0.0005,0.0000,0.5600,1,0.5308,0.0000,0.2603,26900,PrivacySuppressed
TX,Angelo State University,San Angelo,0.0,0.0,0.0,0,475.0,490.0,0.0,5290.0,...,0.0285,0.0331,0.0011,0.1289,1,0.4068,0.5279,0.1407,37700,21319.5

4.'TX', 'CA', 'NY' 주의 모든 대학을 선택하세요.

In [26]:
states = ['TX', 'CA', 'NY']

In [28]:
college[college['STABBR'].isin(states)].head()

,INSTNM,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
192,Academy of Art University,San Francisco,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0249,0.2523,0.2098,0.4334,1,0.4008,0.5524,0.4043,36000,35093
193,ITT Technical Institute-Rancho Cordova,Rancho Cordova,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0400,0.0000,0.1780,0.2540,0,0.7137,0.7667,0.7235,38800,25827.5
194,Academy of Chinese Culture and Health Sciences,Oakland,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,PrivacySuppressed
195,The Academy of Radio and TV Broadcasting,Huntington Beach,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0000,0.0000,0.0000,0.0000,1,0.9579,1.0000,0.4545,28400,9500
196,Avalon School of Cosmetology-Alameda,Alameda,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,...,0.0553,0.0000,0.0435,0.5099,1,0.7407,0.6768,0.3387,21600,9860

In [31]:
college[college['STABBR'].isin(states)].shape

(1704, 27)

In [32]:
college2.loc[states].head()

,INSTNM,CITY,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,...,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
STABBR,,,,,,,,,,,,,,,,,,,,,
TX,Abilene Christian University,Abilene,0.0,0.0,0.0,1,530.0,545.0,0.0,3572.0,...,0.0454,0.0423,0.0045,0.0468,1,0.2595,0.5527,0.0381,40200,25985
TX,Alvin Community College,Alvin,0.0,0.0,0.0,0,NaN,NaN,0.0,4682.0,...,0.0002,0.0000,0.0143,0.7123,1,0.1549,0.0625,0.2841,34500,6750
TX,Amarillo College,Amarillo,0.0,0.0,0.0,0,NaN,NaN,0.0,9346.0,...,0.0000,0.0001,0.0085,0.6922,1,0.3786,0.1573,0.3431,31700,10950
TX,Angelina College,Lufkin,0.0,0.0,0.0,0,NaN,NaN,0.0,3825.0,...,0.0264,0.0005,0.0000,0.5600,1,0.5308,0.0000,0.2603,26900,PrivacySuppressed
TX,Angelo State University,San Angelo,0.0,0.0,0.0,0,475.0,490.0,0.0,5290.0,...,0.0285,0.0331,0.0011,0.1289,1,0.4068,0.5279,0.1407,37700,21319.5

In [34]:
college2.loc[states].shape

(1704, 26)